#!/bin/bash
#chmod +x /root/imp/tests/run-all-tests.sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Running Full IMP System Test Suite..."

python3 "$SCRIPT_DIR/test-core-functions.py"
python3 "$SCRIPT_DIR/test-security.py"
python3 "$SCRIPT_DIR/test-performance.py"
python3 "$SCRIPT_DIR/test-expansion.py"
python3 "$SCRIPT_DIR/test-self-improvement.py"
python3 "$SCRIPT_DIR/test-code-updater.py"
python3 "$SCRIPT_DIR/test-neural-network.py"
python3 "$SCRIPT_DIR/test-resource-nn.py"
python3 "$SCRIPT_DIR/test-neural-manager.py"
python3 "$SCRIPT_DIR/test-nn-menu.py"
python3 "$SCRIPT_DIR/test-network-task-nn.py"
python3 "$SCRIPT_DIR/test-network-task-trainer.py"
python3 "$SCRIPT_DIR/test-network-task-engine.py"
python3 "$SCRIPT_DIR/test-defense-nn.py"
python3 "$SCRIPT_DIR/test-defense-trainer.py"
python3 "$SCRIPT_DIR/test-defense-engine.py"
python3 "$SCRIPT_DIR/test-bbi-engine.py"
python3 "$SCRIPT_DIR/test-collaboratory-nn.py"
python3 "$SCRIPT_DIR/test-3d-network.py"
python3 "$SCRIPT_DIR/test-optimal-path.py"
python3 "$SCRIPT_DIR/test-adversarial-trainer.py"
python3 "$SCRIPT_DIR/test-model-analysis.py"
python3 "$SCRIPT_DIR/test-automated-defense.py"
python3 "$SCRIPT_DIR/test-hardware-guard.py"
python3 "$SCRIPT_DIR/test-intranet.py"
python3 "$SCRIPT_DIR/test-metacognition.py"
python3 "$SCRIPT_DIR/test-config.py"
python3 "$SCRIPT_DIR/test-logs.py"
python3 "$SCRIPT_DIR/test-install.py"
python3 "$SCRIPT_DIR/test-bug-hunter.py"
python3 "$SCRIPT_DIR/test-mode-advisor.py"
python3 "$SCRIPT_DIR/test-adaptive-planner.py"
python3 "$SCRIPT_DIR/test-message-bus.py"
python3 "$SCRIPT_DIR/test-goal-chat.py"
python3 "$SCRIPT_DIR/test-node-communicator.py"
python3 "$SCRIPT_DIR/test-distributed-queue.py"
python3 "$SCRIPT_DIR/test-distributed-memory.py"
python3 "$SCRIPT_DIR/test-secure-node-manager.py"
python3 "$SCRIPT_DIR/test-game-copilot.py"
python3 "$SCRIPT_DIR/test-auth.py"
python3 "$SCRIPT_DIR/test-mood.py"
python3 "$SCRIPT_DIR/test-mood-cli.py"
python3 "$SCRIPT_DIR/test-motivation.py"
python3 "$SCRIPT_DIR/test-voice.py"
python3 "$SCRIPT_DIR/test-voice-menu.py"
python3 "$SCRIPT_DIR/test-speech.py"
python3 "$SCRIPT_DIR/test-network-auditor.py"
python3 "$SCRIPT_DIR/test-network-monitor.py"
python3 "$SCRIPT_DIR/test-windows-support.py"
python3 "$SCRIPT_DIR/test-blockchain-ledger.py"
python3 "$SCRIPT_DIR/test-self-healer.py"
python3 "$SCRIPT_DIR/test-auto-heal.py"
python3 "$SCRIPT_DIR/test-backup-restore.py"
python3 "$SCRIPT_DIR/test-chained-workflow.py"
python3 "$SCRIPT_DIR/test-code-map.py"
python3 "$SCRIPT_DIR/test-debug-sandbox.py"

echo "All Tests Completed!"
